# * HQNet constants
SAMPLING_DENSITY = 200
CNET_TRAIN_SIZE = 3000
CNET_TEST_SIZE = 500
CNET_HIDDEN_DIM = 100
CNET_CONV_NCHAN = 4

QNET_HIDDEN_DIM = 100
QNET_BATCH_SIZE = 100
QNET_TRAIN_SIZE = 0 # TODO

Q_MODE_NM = 'nm' # Nelder-Mead
Q_MODE_GD = 'gd' # SGD
Q_MODE_ADAM = 'adam'
Q_MODES = (Q_MODE_NM, Q_MODE_GD, Q_MODE_ADAM)
