#!/bin/bash
#SBATCH -J DS-L4-XY
#SBATCH -n 24
#SBATCH -t 5-00:00:00
#SBATCH -p shared
#SBATCH --mem-per-cpu=4000
#SBATCH -o DS-XY_%j.out
#SBATCH -e er_DS-XY_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jlu@college.harvard.edu
source activate $HOME/anaconda_env
APP_DIR="/n/home04/jzlu/symmetry-learning/"
module list
echo "Starting calculations..."
python3 $APP_DIR/DScaling.py -L 4 -v -x XY ${SLURM_ARRAY_TASK_ID}
echo "Calculations complete!"
