#!/bin/bash
#SBATCH -J LS-d1-XY
#SBATCH -n 24
#SBATCH -t 7-00:00:00
#SBATCH -p shared
#SBATCH --mem-per-cpu=8000
#SBATCH -o LS-XY_%a.out
#SBATCH -e er_LS-XY_%a.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jlu@college.harvard.edu
source activate $HOME/anaconda_env
APP_DIR="/n/home04/jzlu/symmetry-learning/"
module list
echo "Starting calculations..."
python3 $APP_DIR/LScaling.py -d 1 -n 10 -x XY ${SLURM_ARRAY_TASK_ID}
echo "Calculations complete!"
