#!/bin/bash
#SBATCH -J CC-XY
#SBATCH -n 24
#SBATCH -t 5-00:00:00
#SBATCH -p shared
#SBATCH --mem-per-cpu=4000
#SBATCH -o CC-XY_%j.out
#SBATCH -e er_CC-XY_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jlu@college.harvard.edu
source activate $HOME/anaconda_env
APP_DIR="/n/home04/jzlu/symmetry-learning/"
module list
echo "Starting calculations..."
python3 $APP_DIR/CircComp.py -v -d ${SLURM_ARRAY_TASK_ID} -x 50 XY
echo "Calculations complete!"
