#!/bin/bash
#SBATCH -J LS-d2-GHZ
#SBATCH -n 24
#SBATCH -t 5-00:00:00
#SBATCH -p shared
#SBATCH --mem-per-cpu=4000
#SBATCH -o LS-GHZ_%j.out
#SBATCH -e er_LS-GHZ_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jlu@college.harvard.edu
source activate $HOME/anaconda_env
APP_DIR="/n/home04/jzlu/symmetry-learning/"
module list
echo "Starting calculations..."
python3 $APP_DIR/LScaling.py -d 2 -n 10 GHZ ${SLURM_ARRAY_TASK_ID}
echo "Calculations complete!"
